version: '3.0'
services:
  ###########################
  # Kong & Kong Database #
  ###########################
  kong-db:
    container_name: kong-db
    image: postgres:12
    environment:
      POSTGRES_DB: "${KONG_PG_DATABASE}"
      POSTGRES_USER: "${KONG_PG_USER}"
      POSTGRES_PASSWORD: "${KONG_PG_PASSWORD}"
    ports:
      - "5433:5432"
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong-migration:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "${KONG_PG_HOST}"
      KONG_PG_DATABASE: "${KONG_PG_DATABASE}"
      KONG_PG_USER: "${KONG_PG_USER}"
      KONG_PG_PASSWORD: "${KONG_PG_PASSWORD}"
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    depends_on:
      - kong-db
    restart: on-failure

  kong-migration-up:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "${KONG_PG_HOST}"
      KONG_PG_DATABASE: "${KONG_PG_DATABASE}"
      KONG_PG_USER: "${KONG_PG_USER}"
      KONG_PG_PASSWORD: "${KONG_PG_PASSWORD}"
    command: "kong migrations up && kong migrations finish"
    networks:
      - kong-net
    depends_on:
      - kong-db
    restart: on-failure

  kong:
    container_name: kong
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "${KONG_PG_HOST}"
      KONG_PG_DATABASE: "${KONG_PG_DATABASE}"
      KONG_PG_USER: "${KONG_PG_USER}"
      KONG_PG_PASSWORD: "${KONG_PG_PASSWORD}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    depends_on:
      - kong-db
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    restart: on-failure

  ###########################
  # Konga & Konga Database #
  ###########################
  konga-db:
    container_name: konga-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${KONGA_DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${KONGA_DB_PASSWORD}"
    volumes:
      - konga_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - kong-net

  konga:
    image: pantsel/konga:latest
    environment:
      DB_ADAPTER: "${KONGA_DB_ADAPTER}"
      DB_URI: "${KONGA_DB_URI}"
      NODE_ENV: "${KONGA_NODE_ENV}"
      TOKEN_SECRET: "${KONGA_TOKEN_SECRET}"
    depends_on:
      - konga-db
    networks:
      - kong-net
    ports:
      - "1337:1337"
    restart: on-failure
volumes:
  kong_data:
  konga_data:
networks:
  kong-net:
    external: true