version: '3.0'
services:
  kong-db:
    container_name: kong-db
    image: postgres:12
    environment:
      POSTGRES_DB: "${KONG_PG_DATABASE}"
      POSTGRES_USER: "${KONG_PG_USER}"
      POSTGRES_PASSWORD: "${KONG_PG_PASSWORD}"
    ports:
      - "5433:5432"
    networks:
      - kong-net
    volumes:
      - "kong-db-data"
  kong-migration:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "${KONG_PG_HOST}"
      KONG_PG_DATABASE: "${KONG_PG_DATABASE}"
      KONG_PG_USER: "${KONG_PG_USER}"
      KONG_PG_PASSWORD: "${KONG_PG_PASSWORD}"
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    depends_on:
      - kong-db
  kong:
    container_name: kong
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: "${KONG_PG_HOST}"
      KONG_PG_DATABASE: "${KONG_PG_DATABASE}"
      KONG_PG_USER: "${KONG_PG_USER}"
      KONG_PG_PASSWORD: "${KONG_PG_PASSWORD}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    depends_on:
      - kong-migration
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  konga-db:
    container_name: konga-db
    image: postgres:12
    environment:
      POSTGRES_DB: "${KONGA_PG_DATABASE}"
      POSTGRES_USER: "${KONGA_PG_USER}"
      POSTGRES_PASSWORD: "${KONGA_PG_PASSWORD}"
    ports:
      - "5434:5432"
    networks:
      - kong-net
    volumes:
      - "konga-db-data"
    depends_on:
      - kong
  konga-preparation:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://konga@konga-db:5434/konga"
    depends_on:
      - konga-db
    networks:
      - kong-net
  konga:
    image: pantsel/konga:latest
    environment:
      DB_ADAPTER: postgres
      DB_HOST: "${KONGA_PG_HOST}"
      DB_DATABASE: "${KONGA_PG_DATABASE}"
      DB_USER: "${KONGA_PG_USER}"
      DB_PASSWORD: "${KONGA_PG_PASSWORD}"
      NODE_ENV: "${KONGA_NODE_ENV}"
      TOKEN_SECRET: "${KONGA_TOKEN_SECRET}"
    depends_on:
      - konga-preparation
    networks:
      - kong-net
    ports:
      - "1337:1337"
volumes:
  kong-db-data:
  konga-db-data:
networks:
  kong-net:
    external: true